spring:
  application:
    name: batchdemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batchdb
    username: root
    password: mysqldb@3306

  batch:
    job:
      enabled: true
      name: demoJob